"""soft delete chat user ai-conversation

Revision ID: 02fe8011cb86
Revises: cf748eccff26
Create Date: 2025-09-27 22:45:42.068482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02fe8011cb86'
down_revision: Union[str, Sequence[str], None] = 'cf748eccff26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_conversations', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('ai_conversations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chats', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('chats', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('chats', 'deleted_at')
    op.drop_column('chats', 'is_deleted')
    op.drop_column('ai_conversations', 'deleted_at')
    op.drop_column('ai_conversations', 'is_deleted')
    # ### end Alembic commands ###
