"""Create chats and messages tables

Revision ID: 0a1c2a1c50a7
Revises: b3eb471c4146
Create Date: 2025-08-21 00:23:50.705583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1c2a1c50a7'
down_revision: Union[str, Sequence[str], None] = 'b3eb471c4146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
