"""add_missing_platform_column

Revision ID: 1990bd6eec45
Revises: 8a01cc25cccd
Create Date: 2025-11-18 22:54:51.589196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1990bd6eec45'
down_revision: Union[str, Sequence[str], None] = '8a01cc25cccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('platform', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'platform')
    # ### end Alembic commands ###
