"""chat-insights-unlock-status

Revision ID: 1b53f5c14067
Revises: bcb4054da0d3
Create Date: 2025-11-05 23:35:05.758653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b53f5c14067'
down_revision: Union[str, Sequence[str], None] = 'bcb4054da0d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight_generation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_insights', sa.Integer(), nullable=False),
    sa.Column('completed_insights', sa.Integer(), nullable=True),
    sa.Column('failed_insights', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estimated_completion_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=True),
    sa.Column('total_generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('failed_insight_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['analysis_categories.id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_generation_jobs_job_id'), 'insight_generation_jobs', ['job_id'], unique=True)
    op.add_column('chats', sa.Column('insights_unlocked_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('chats', sa.Column('insights_generation_status', sa.String(), nullable=False))
    op.add_column('chats', sa.Column('insights_generation_started_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('chats', sa.Column('insights_generation_completed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('chats', sa.Column('insights_job_id', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('total_insights_requested', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('total_insights_completed', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('total_insights_failed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'total_insights_failed')
    op.drop_column('chats', 'total_insights_completed')
    op.drop_column('chats', 'total_insights_requested')
    op.drop_column('chats', 'insights_job_id')
    op.drop_column('chats', 'insights_generation_completed_at')
    op.drop_column('chats', 'insights_generation_started_at')
    op.drop_column('chats', 'insights_generation_status')
    op.drop_column('chats', 'insights_unlocked_at')
    op.drop_index(op.f('ix_insight_generation_jobs_job_id'), table_name='insight_generation_jobs')
    op.drop_table('insight_generation_jobs')
    # ### end Alembic commands ###
