"""rag query template, chat metadata, partner_name

Revision ID: 1c4f9caa6100
Revises: 81a05243ff55
Create Date: 2025-10-08 22:06:12.028720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4f9caa6100'
down_revision: Union[str, Sequence[str], None] = '81a05243ff55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('chat_metadata', sa.JSON(), nullable=True))
    op.add_column('chats', sa.Column('partner_name', sa.String(), nullable=True))
    op.add_column('insight_types', sa.Column('rag_query_keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insight_types', 'rag_query_keywords')
    op.drop_column('chats', 'partner_name')
    op.drop_column('chats', 'chat_metadata')
    # ### end Alembic commands ###
