"""participants, user display name, error log in chat table

Revision ID: 516267383bc5
Revises: 561b148efe38
Create Date: 2025-08-23 00:06:04.914181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516267383bc5'
down_revision: Union[str, Sequence[str], None] = '561b148efe38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('participants', sa.Text(), nullable=True))
    op.add_column('chats', sa.Column('user_display_name', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('error_log', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'error_log')
    op.drop_column('chats', 'user_display_name')
    op.drop_column('chats', 'participants')
    # ### end Alembic commands ###
