"""cascade message on chat and on user delete

Revision ID: 530afe9d286e
Revises: 516267383bc5
Create Date: 2025-08-23 19:59:19.558444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '530afe9d286e'
down_revision: Union[str, Sequence[str], None] = '516267383bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chats_user_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_user_id_fkey'), 'chats', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
