"""response schema and required metadata fields in insight type

Revision ID: 5f722edaa57c
Revises: 1c4f9caa6100
Create Date: 2025-10-10 00:33:29.980342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f722edaa57c'
down_revision: Union[str, Sequence[str], None] = '1c4f9caa6100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insight_types', sa.Column('response_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('insight_types', sa.Column('required_metadata_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insight_types', 'required_metadata_fields')
    op.drop_column('insight_types', 'response_schema')
    # ### end Alembic commands ###
