"""add_coin_reservation

Revision ID: 74fa35a438a5
Revises: 8527a1e4d4ec
Create Date: 2025-11-15 07:46:00.138931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74fa35a438a5'
down_revision: Union[str, Sequence[str], None] = '8527a1e4d4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('reserved_coins', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('reservation_expires_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('insight_generation_jobs', sa.Column('payment_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insight_generation_jobs', 'payment_status')
    op.drop_column('chats', 'reservation_expires_at')
    op.drop_column('chats', 'reserved_coins')
    # ### end Alembic commands ###
