"""payment tables add again

Revision ID: 8527a1e4d4ec
Revises: 01a889923448
Create Date: 2025-11-12 14:25:20.624750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8527a1e4d4ec'
down_revision: Union[str, Sequence[str], None] = '01a889923448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('RAZORPAY', 'STRIPE', name='paymentprovider'), nullable=False),
    sa.Column('provider_order_id', sa.String(), nullable=True),
    sa.Column('provider_payment_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('payment_order_metadata', sa.JSON(), nullable=True),
    sa.Column('webhook_received_at', sa.DateTime(), nullable=True),
    sa.Column('webhook_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_orders_idempotency_key'), 'payment_orders', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_payment_orders_provider_order_id'), 'payment_orders', ['provider_order_id'], unique=True)
    op.create_index(op.f('ix_payment_orders_provider_payment_id'), 'payment_orders', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_payment_orders_status'), 'payment_orders', ['status'], unique=False)
    op.create_index(op.f('ix_payment_orders_user_id'), 'payment_orders', ['user_id'], unique=False)
    op.create_table('payment_refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_order_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('RAZORPAY', 'STRIPE', name='paymentprovider'), nullable=False),
    sa.Column('provider_refund_id', sa.String(), nullable=True),
    sa.Column('provider_payment_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('coins_refunded', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('payment_refund_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_refunds_payment_order_id'), 'payment_refunds', ['payment_order_id'], unique=False)
    op.create_index(op.f('ix_payment_refunds_provider_refund_id'), 'payment_refunds', ['provider_refund_id'], unique=True)
    op.create_index(op.f('ix_payment_refunds_user_id'), 'payment_refunds', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_refunds_user_id'), table_name='payment_refunds')
    op.drop_index(op.f('ix_payment_refunds_provider_refund_id'), table_name='payment_refunds')
    op.drop_index(op.f('ix_payment_refunds_payment_order_id'), table_name='payment_refunds')
    op.drop_table('payment_refunds')
    op.drop_index(op.f('ix_payment_orders_user_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_status'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_provider_payment_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_provider_order_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_idempotency_key'), table_name='payment_orders')
    op.drop_table('payment_orders')
    # ### end Alembic commands ###
