"""group chat support in models

Revision ID: 898d6fb66dfa
Revises: 1b53f5c14067
Create Date: 2025-11-08 22:00:09.174718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898d6fb66dfa'
down_revision: Union[str, Sequence[str], None] = '1b53f5c14067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('is_group_chat', sa.Boolean(), nullable=False))
    op.add_column('chats', sa.Column('participant_count', sa.Integer(), nullable=True))
    op.add_column('insight_types', sa.Column('supports_group_chats', sa.Boolean(), nullable=False))
    op.add_column('insight_types', sa.Column('max_participants', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insight_types', 'max_participants')
    op.drop_column('insight_types', 'supports_group_chats')
    op.drop_column('chats', 'participant_count')
    op.drop_column('chats', 'is_group_chat')
    # ### end Alembic commands ###
