"""datetime.now(timezone.utc)

Revision ID: 8a01cc25cccd
Revises: 74fa35a438a5
Create Date: 2025-11-16 21:12:37.877042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a01cc25cccd'
down_revision: Union[str, Sequence[str], None] = '74fa35a438a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
