"""add vector fields to chats and messagechunk table

Revision ID: 8dfe7461b138
Revises: 530afe9d286e
Create Date: 2025-08-29 23:47:39.373759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dfe7461b138'
down_revision: Union[str, Sequence[str], None] = '530afe9d286e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('vector_id', sa.String(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_chunks_id'), 'message_chunks', ['id'], unique=False)
    op.add_column('chats', sa.Column('vector_status', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('indexed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('chats', sa.Column('chunk_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'chunk_count')
    op.drop_column('chats', 'indexed_at')
    op.drop_column('chats', 'vector_status')
    op.drop_index(op.f('ix_message_chunks_id'), table_name='message_chunks')
    op.drop_table('message_chunks')
    # ### end Alembic commands ###
