"""add_price_inr_to_credit_packages-credit_cost_in_category

Revision ID: e5ab94ea3203
Revises: 898d6fb66dfa
Create Date: 2025-11-10 22:55:11.268509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5ab94ea3203'
down_revision: Union[str, Sequence[str], None] = '898d6fb66dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_categories', sa.Column('credit_cost', sa.Integer(), nullable=False))
    op.add_column('credit_packages', sa.Column('price_inr', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_packages', 'price_inr')
    op.drop_column('analysis_categories', 'credit_cost')
    # ### end Alembic commands ###
