-- 1. Conflict Resolution Style Insight Type (Corrected)
INSERT INTO insight_types (id, name, display_title, description, icon, prompt_template, is_premium, credit_cost, is_active)
VALUES (
    gen_random_uuid(), -- Ensures a new UUID is generated by the database
    'conflict_analysis',
    'Conflict Resolution Style',
    'Analyzes how conflicts are initiated, handled, and resolved, identifying destructive or constructive patterns.',
    '💥',
    'You are a relationship expert. Analyze the conversation history provided below for conflict resolution patterns. Identify the style of each participant (e.g., accommodating, competing, compromising, avoiding, collaborating) and provide a summary of your findings in JSON format.',
    FALSE,
    1,
    TRUE
);

-- 2. Communication Style & Tone Insight Type (Corrected)
INSERT INTO insight_types (id, name, display_title, description, icon, prompt_template, is_premium, credit_cost, is_active)
VALUES (
    gen_random_uuid(), -- Ensures a new UUID is generated by the database
    'communication_patterns',
    'Communication Style & Tone',
    'Evaluates the overall tone, politeness, and active listening skills displayed by the users in the conversation.',
    '🗣️',
    'Analyze the conversation for communication patterns. Focus on identifying tone (positive, negative, neutral), the use of "I" vs "You" statements, and evidence of active listening. Generate a report in JSON format summarizing the distinct communication style of each party.',
    TRUE, -- Example of a premium insight
    3,
    TRUE
);

-- 3. Relationship Health & Indicators Insight Type (Corrected)
INSERT INTO insight_types (id, name, display_title, description, icon, prompt_template, is_premium, credit_cost, is_active)
VALUES (
    gen_random_uuid(), -- Ensures a new UUID is generated by the database
    'relationship_indicators',
    'Relationship Health & Indicators',
    'Highlights positive "Green Flags" (e.g., support, validation) and potential "Red Flags" (e.g., stonewalling, criticism) in the conversation.',
    '🚦',
    'Search the provided chat log for both Green Flags (supportive, affirming, appreciative language) and Red Flags (dismissive, controlling, critical language). List the top 3 of each category with a supporting quote from the chat in a structured JSON object.',
    FALSE,
    1,
    TRUE
);